### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by atumas-bananamilk** [suprsend/suprsend-react-inbox#50]
What's the issue?
We're trying to use your library:

![Screenshot 2024-06-10 at 23 12 05](https://github.com/suprsend/suprsend-react-inbox/assets/22228431/e22e07a6-ac93-4ea1-a8b6-73219ab1140b)

![Screenshot 2024-06-10 at 23 03 56](https://github.com/suprsend/suprsend-react-inbox/assets/22228431/60a3f7f3-bccd-4b75-aba4-268fe18317de)

**Comment by gauravverma** [comment]
@sivaram000 please check this.

**Comment by sivaram000** [comment]
Checking..

**Comment by sivaram000** [comment]
Hi @atumas-bananamilk 
The error was happening in nextjs because global styles importing by node_modules is supported in nextjs. (https://github.com/vercel/next.js/issues/19936)

Please upgrade `@suprsend/react-inbox` to v3.2.0. and add `import 'react-toastify/dist/ReactToastify.css'` line along with SuprSendInbox  component import. https://docs.suprsend.com/docs/inbox-react#integration

Let us know if you face any issue.
